main: dev.kittycore.App
name: Kittycore
version: 0.1

commands:
  balance:
    description: Get the amount of money you currently have
    usage: /balance
  pay:
    description: Pay money to some user
    usage: /pay <player> [amount]
  spawn:
    description: Return to the spawn world (you need to pay 10 euros)
    usage: /spawn
  gamble:
    description: Gamble your hard earned money 
    usage: /gamble <amount>
  top:
    description: Get the top 5 players (by money)
    usage: /top

